@startuml
top to bottom direction
component "Patient Table" as pt

package Pedals{
component "Low Dose Pedal" as p1
component "High Dose Pedal" as p2
}

package "X-ray Hardware"{
component "X-ray tube" as xt
component "X-ray detector" as xd

interface "X-ray \ninput" as Xray1
interface "X-ray \noutput" as Xray2
}

component Screen as scr
component Tablet as ta

component "Pedal Mapper" as pm
component "Action Logic" as al
component "Xray Controller" as xc
component "Image Processor" as ip
component "System Configurator" as sc
component "Procedure Database" as pd



interface "Optical information" as xi
interface "Pedal actions" as pa
interface "X-ray request" as xr
interface "X-ray command" as xcm
interface "(De)activate command" as dac
interface "X-ray graph" as xg
interface "Readable image" as ri
interface "All configuration and setting" as acas
interface "Chosen configuration and procedure" as ccas
interface "System Configuration" as syco
interface "Medical procedure" as mp

xt -left- Xray1
Xray1 )-down- pt
pt -up- Xray2
Xray2 )-left- xd
xd -up- xi


p1 -down- pa
p2 -down- pa

pa )-down- pm
pm -down- xr
xr )-down- al
al --down-- xcm
xcm )-right- xc

xc -down-> dac
dac )-down- xt
xi )-up- xc

xc - xg
xg )- ip
ip - ri
ri )-right- scr

pd -down- acas
acas )-down- ta
ta -down- ccas
ccas )-down- sc

sc -down- syco
sc -down- mp
syco )-down- xc
mp -down- ip
@enduml