@startuml
class "Medical_Procedure" as mp{
+procedure_name: String
+procedure_version: String
+procedure_publisher: String
}

class "Xray_Controller_Setting" as xcs{
-low_dose_xray_activated: bool
-high_dose_xray_activated: bool
-timed_pulses_frequency: int
-xray_intensity: int
-xray_resolution: int
}

class "Image_Processor_Setting" as ips{
-input_image_size: int
-input_image_resolution: int
-output_image_size: int
-output_image_resolution: int
-output_image_type: int
-output_image_colored: bool
}


mp <|-down- xcs
mp <|-down- ips

class "Database" as db{
+database_size: int
+procedure_num: int
}

db "1" *-down- "1..*"mp


@enduml