/*
 * generated by Xtext 2.29.0
 */
package xray.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class XRayDSLUiModule extends AbstractXRayDSLUiModule {
}
